language: python
# with next we get on container based infrastructure, this enables caching
sudo: false
python:
  - 2.7
cache:
  pip: true
  directories:
    - downloads
    - eggs
env:
  - PLONE_VERSION=5.1.x SOLR_VERSION=4.10.x
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - virtualenv .
  - bin/pip install --upgrade -r requirements.txt
  - bin/pip install zest.pocompile
  - bin/pocompile src
install:
  - sed -ie "s#plone-x.x.x.cfg#plone-$PLONE_VERSION.cfg#" travis.cfg
  - sed -ie "s#solr-x.x.x.cfg#solr-$SOLR_VERSION.cfg#" travis.cfg
  - bin/buildout -N -t 20 -c travis.cfg buildout:download-cache=downloads
script:
  - bin/code-analysis
  - bin/coverage run bin/test
  # Run Robot Framework in isolation to avoid test isolation issues.
  # - export ROBOTSUITE_PREFIX=ONLYROBOT && bin/test -t ONLYROBOT --all
after_success:
  - pip install -q coveralls python-coveralls==2.5.0
  - coveralls
